Undo flake8 E402, to avoid circular export
ImportError: cannot import name 'CallbackRegistry' from partially initialized module 'chemprop.callbacks' (most likely due to a circular import) (chemprop/chemprop/callbacks/__init__.py)